name = "dormexchange"

# Cloudflare Pages: where next-on-pages outputs the static assets
pages_build_output_dir = ".vercel/output/static"

# Edge runtime compatibility
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

# Do not put secrets here; set them in the Cloudflare Pages dashboard.
